server:
  port: 8099

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fengyin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: 
    password: 
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 18000000
      connection-test-query: SELECT 1
  data:
    mongodb:
      uri:
      database: fengyin
  rabbitmq:
    host:
    port: 5672
    username: admin
    password:
    virtual-host: fengyin

  redis:
    host: 
    password: 
    port: 6379
    database: 0

minio:
  endpoint: 
  fileHost:
  bucketName: fengyin
  accessKey:
  secretKey:
  imgSize: 1024
  fileSize: 1024
